### ISSUE TITLE
devserver stopped working with django 1.5.5

### ISSUE THREAD

**Issue by syphar** [dcramer/django-devserver#91]
When running devserver with django 1.5.5, I get: 

```
    from django.core.servers.basehttp import WSGIServerException, WSGIServer
ImportError: cannot import name WSGIServerException
```

This exception was completely removed in Django itself (https://github.com/django/django/commit/18fe77e4ed01a7761a24de7ec7b1c3a1314fc197)
